### ISSUE TITLE
“PR fix” can only fix to the nearest version at a time, why not fix the highest version directly

### ISSUE THREAD

**Issue by liwei2151284** [jfrog/frogbot#117]
“PR fix” can only fix to the nearest version at a time, why not fix the highest version directly

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/16078620/182818118-0f17d81e-9b50-40d7-9697-7a2c6d059a4f.png">

The risk of scanning 4 fastjson after MR, the repair version includes 1.2.60, 1.2.61, 1.2.69, 1.2.83, why can't it be directly repaired to 1.2.83, but need to raise 4 PRs from 1.2.60 to 1.2.83

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/16078620/182818176-68730646-2a24-45cb-9748-6258bd8ce093.png">

**Comment by omerzi** [comment]
Hello @liwei2151284, thanks for letting us know about this. This issue will be fixed and I will keep you posted on the progress.

**Comment by liwei2151284** [comment]
@omerzi  Sorry, I forgot to reply last week, thank you for your support

**Comment by omerzi** [comment]
Hi @liwei2151284, we have just released v2.2.1 which fixes this issue.
Thanks for your time, and please let me know if you have any more questions.
