### ISSUE TITLE
Support Git on Azure Devops Server

### ISSUE THREAD

**Issue by justminime** [jfrog/frogbot#134]
**Is your feature request related to a problem? Please describe.**
We areworking on closed environment (no internet) and want to use the frogbot on our azure devops 2020 on premise that would connect to our on-premise Jfrog server (xray+artifactory)

**Describe the solution you'd like to see**
add azure devops git to the guthub\gitlab\bitbucket options

**Describe alternatives you've considered**

**Comment by Jan-Pleva** [comment]
+1 for onprem Azure DevOps Server + JFrog onprem.

**Comment by Jan-Pleva** [comment]
That's great! Can we deploy to Azure DevOps server?

**Comment by eyalbe4** [comment]
Frogbot with Support for scanning Azure Repos is now available. See the documentation for installation and usage details 
@Jan-Pleva - Frogbot doesn't perform deployments. It scans your repositories and pull requests for security vulnerabilities.

**Comment by anael-l** [comment]
Hello, I have tested it on our on prem instance of Azure DevOps server, however, there seems to be places in the code with the Hardcorded URL of Azure DevOps Cloud:

`
15:03:21 [Info] Xray scan completed
15:03:21 [Debug] Upload Scan to Azure Repos is currently unsupported.
15:03:21 [Info] Found 3 vulnerable dependencies with fix versions
15:03:21 [Debug] Created temp working directory: /tmp/jfrog.cli.temp.-1674655401-4193977151
15:03:51 [Error] repository (REDACTED) returned the following error:

'git clone master from https://(REDACTED)@dev.azure.com/(REDACTED)/(REDACTED)/_git/(REDACTED)' failed with error: Get "https://(REDACTED)@dev.azure.com/(REDACTED)/(REDACTED)/_git/(REDACTED)/info/refs?service=git-upload-pack": dial tcp 13.107.42.20:443: i/o timeout
`

**Comment by omerzi** [comment]
Thank you for reporting this, @anael-l. I'm investigating it and will update as soon as possible.

**Comment by omerzi** [comment]
Hi @anael-l, do you use Azure Repos?

According to Microsoft's documentation, Azure Repos Clone URLs contain "dev.azure.com", as you can see here [here](https://learn.microsoft.com/en-us/azure/devops/repos/git/clone?view=azure-devops-2019&tabs=visual-studio-2022) ("Get the clone URL of an Azure Repos Git repo" -> 3rd picture).

Did we miss anything? Thanks!

**Comment by anael-l** [comment]
Hi @omerzi, yes you've got the right doc, but I don't think Microsoft made an effort to change the doc for the Server version, as it's exactly the same for the cloud version on this page...
On our instance, the repo URL constructed like this : 

https://[custom-domain]/[collection]/[team-project/_git/[repo]

The weird thing is that the first clone froggit does using the API works :

`
15:01:05 [Info] Running Frogbot "scan-and-fix-repos" command 
15:01:05 [Debug] Usage Report: Sending info...
15:01:05 [Debug] Created temp working directory:  /tmp/jfrog.cli.temp.-1674655265-4257864351
15:01:05 [Debug] Downloading (Collection)/(RepoName), branch: master to: /tmp/jfrog.cli.temp.-1674655265-4257864351
15:01:05 [Debug] download url: https://(CustomDomain)/(Collection)/(TeamProject)/_apis/git/repositories/(RepoName)/items/items?path=/&versionDescriptor[version]=master&$format=zip
15:01:05 [Debug] Sending HTTP GET request to: https://(artifactorydns)/artifactory/api/system/version
15:01:05 [Debug] Artifactory response: 200 
[...]
`

I think you should use the environment variable JF_GIT_API_ENDPOINT as it might be the case for the clone using the API

**Comment by omerzi** [comment]
Thanks, @anael-l for clarifying that. So just to be clear, when you need to clone using the git command line, as it's the command that fails on frogbot, the command looks something like this:
`git clone https://[custom-domain]/[collection]/[team-project]/_git/[repo]`
Or like this:
`git clone https://[collection]@[custom-domain]/[collection]/[project]/_git/[repo]`

**Comment by anael-l** [comment]
I've always used the first one 
`git clone https://[custom-domain]/[collection]/[team-project]/_git/[repo]`
As it is the one provided in the **Clone Repository** popup as shown in the Microsoft documentation.
However out of curiosity I tested the second one, and it also seems to work.

**Comment by omerzi** [comment]
My sincere thanks go out to you for your assistance. I have opened a Pull Request with the following changes:

https://github.com/jfrog/froggit-go/pull/65

I'll update once Frogbot is released with the updated froggit-go dependency.

**Comment by anael-l** [comment]
Thank you for the fast anwsers and fix !
I will test it once it is available

**Comment by omerzi** [comment]
@anael-l, [v2.5.5](https://github.com/jfrog/frogbot/releases/tag/v2.5.5) is released. Please let me know if it works, thank you!

**Comment by anael-l** [comment]
It works ! Thank you very much !

`16:35:14 [Info] Frogbot "scan-and-fix-repos" command finished successfully`
