### ISSUE TITLE
support XRay scan for repositories containing multiple projects (so called mono-repo)

### ISSUE THREAD

**Issue by philipp-rauch-se** [jfrog/frogbot#168]
**Is your feature request related to a problem? Please describe.**
I would like to use JFrog XRay to scan Pull Requests. 
The source code repository containing multiple projects with different programming languages (dotnet, Angular, ...), so called mono-repo:
![image](https://user-images.githubusercontent.com/116552558/197518891-dfc5b91d-caef-4e82-8da3-5c3f830b7655.png)

This can be dozens projects per repository. Currently frogbot seems to be prepared only for exactly one JF_PROJECT_WORKING_DIR and JF_INSTALL_DEPS_CMD. We are aware that we could have separate workflows for each project. 
But you can image that its frustrating or even not usable when you have dozens of projects, dozens of scans must be approved manually and dozens separate comments are added to the Pull Request

**Describe the solution you'd like to see**
A solution to have only ONE scan for a Pull Request of a repository containing different projects with multiple languages as shown above. For example JF_PROJECT_WORKING_DIR and JF_INSTALL_DEPS_CMD could support comma separated values to specify multiple projects with multiple install commands

If you need more information don't hesitate to contact me. Many thanks in advance, 
Philipp

**Comment by omerzi** [comment]
Hi @philipp-rauch-se, thank you for using Frogbot and helping us improve. I am currently working on implementing this feature and will keep you posted once I've made progress.

**Comment by philipp-rauch-se** [comment]
Hi @omerzi, thanks you very much. Its in use now and looks very good 👍
