### ISSUE TITLE
when running frogbot locally, scan-pull-requests trying to query issues that don't exist...

### ISSUE THREAD

**Issue by tomhmc** [jfrog/frogbot#179]
**Describe the bug**
When trying to run locally, I am seeing an error where scan-pull-requests is trying to pull comments for an issue that doesn't exist and failing.

**To Reproduce**
This is using github enterprise server, and running the frogbot locally

```
√ frogbot % go run main.go scan-pull-requests
13:57:11 [Info] Running Frogbot "scan-pull-requests" command
13:57:11 [Debug] Usage Report: Sending info...
13:57:11 [Debug] Sending HTTP GET request to: https://my.jfrog/artifactory/api/system/version
13:57:11 [Debug] Artifactory response: 200 OK
13:57:11 [Debug] JFrog Artifactory version is: 7.41.12
13:57:11 [Debug] Sending HTTP POST request to: https://my.jfrog/artifactory/api/system/usage
13:57:11 [Debug] Usage Report: Artifactory response: 200 OK
13:57:11 [Debug] Usage Report: Usage info sent successfully.
13:57:11 [Error] GET https://my.github.enterprise/api/v3/repos/org1/repo1/issues/12345/comments: 404 Not Found []
13:57:11 [Error] GET https://my.github.enterprise/api/v3/repos/org1/repo1/issues/12345/comments: 404 Not Found []
exit status 1
```

**Expected behavior**
Would get as far as scanning a pull request

**Versions**

- Frogbot version: v2
- Operating system :s- JFrog Artifactory version:

```
√ frogbot % sw_vers
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
```

- JFrog Xray version (version 3.29.0 or above is required): 7.41.12

**Additional context**

**Comment by omerzi** [comment]
Hi @tomhmc,
Could you please share which CI server you are using to run Frogbot? 
Currently, scan-pull-requests work on Bitbucket Server with Jenkins or JFrog Pipelines CI servers.
