### ISSUE TITLE
Suppress multiple identical frogbot comments on PRs

### ISSUE THREAD

**Issue by tomhmc** [jfrog/frogbot#185]
**Is your feature request related to a problem? Please describe.**
When a PR is opened, and changes are requested by approvers, there can be quite a few additional commits to the PR branch. This results in many repeating frogbot comments on the PR

**Describe the solution you'd like to see**
Check if comment is a duplicate and suppress in that case.

**Describe alternatives you've considered**
Open to suggestions...

**Additional context**

![Screenshot 2022-11-23 at 17 30 52](https://user-images.githubusercontent.com/103634979/203612283-aa74f94a-d70e-4f86-b757-5b56cb05330c.png)

**Comment by ivanmrva** [comment]
hi, do you have any plans to fix this? this gets really annoying quite fast, when people are working on a MR intensively. We are now having MRs with 15+ frogbot comments, which makes it very difficult to review user comments. At best, just always override the same comment. There is not even need to track changes (e.g. changes from red to green, etc.). For example, Sonarqube analysis will always override the same comment upon every commit/re-analysis, providing a very good overview for users.

**Comment by omerzi** [comment]
Hi @tomhmc and @ivanmrva, I apologize for the delayed response. We greatly appreciate your feedback on Frogbot functionality, and we recognize the importance of addressing this request. I want to assure you that improving the user experience is a priority for us, and this request is definitely on our near-term roadmap.

Based on your feedback, it seems that removing the latest Frogbot comment and replacing it with a newly added updated comment could be a viable approach. We would appreciate hearing your thoughts on this proposed solution. What do you think?

**Comment by neatcoder** [comment]
> Hi @tomhmc and @ivanmrva, I apologize for the delayed response. We greatly appreciate your feedback on Frogbot functionality, and we recognize the importance of addressing this request. I want to assure you that improving the user experience is a priority for us, and this request is definitely on our near-term roadmap.
> 
> Based on your feedback, it seems that removing the latest Frogbot comment and replacing it with a newly added updated comment could be a viable approach. We would appreciate hearing your thoughts on this proposed solution. What do you think?

+1 Please 👌 
Really need this feature

**Comment by omerzi** [comment]
Hey @ivanmrva, @neatcoder, @mpwmc, and @tomhmc,

I wanted to inform you that we have implemented the feature discussed earlier. The changes are included in the following pull request:
https://github.com/jfrog/frogbot/pull/400

Once the PR gets approved, the feature will be included in the upcoming release. I will make sure to keep you all updated on its status. Thank you for your valuable feedback; it has been instrumental in improving our work. Feel free to reach out if you have any further questions or suggestions. Thanks again!

**Comment by omerzi** [comment]
Hi @ivanmrva, @neatcoder, @mpwmc, and @tomhmc,
The issue has been fixed in Frogbot v2.11.3. Thank you all once again for reporting this issue to us. Please let us know if you have any further questions.
