### ISSUE TITLE
Advanced Security issue

### ISSUE THREAD

**Issue by Dzmitry-Varashylau** [jfrog/frogbot#201]
Hello, is there any way to use frogbot without Advanced Security?

```
Run jfrog/frogbot@v2
...
09:20:35 [Warn] upload code scanning failed with: POST https://github.kyndryl.net/api/v3/repos/org-for-tests/back/code-scanning/sarifs: 403 Advanced Security must be enabled for this repository to use code scanning. []
```

**Comment by omerzi** [comment]
@Dzmitry-Varashylau, Frogbot does not require GitHub Advanced Security. If Advanced Security is disabled, Frogbot still continues running and opens a pull request if there are vulnerabilities to fix. You can see that we only printed a warning, but Frogbot did not fail.

**Comment by ismaelhamed** [comment]
@omerzi without GH Advanced Security enabled, where can I see a summary of the scan then? This is the output I'm getting:

```
08:03:17 [Info] Running SCA scan for nuget vulnerable dependencies in /tmp/jfrog.cli.temp.-1705564997-3165178356/src directory...
  08:03:17 [Info] Calculating NuGet dependencies...
  08:03:17 [Info] Dependencies sources were not detected nor 'install' command provided. Running 'restore' command
  08:03:22 [Info] Scanning 219 nuget dependencies...
  08:03:22 [Info] Waiting for scan to complete on JFrog Xray...
  08:03:28 [Info] Xray scan completed
  08:03:28 [Warn] upload code scanning for develop branch failed with: POST ***/code-scanning/sarifs: 403 Advanced Security must be enabled for this repository to use code scanning. []
  08:03:28 [Info] Frogbot "scan-repository" command finished successfully
```

It should've found one vulnerability that exists, but it's not opening any PRs. So I'm not sure if the problem is that it didn't find the vulnerability or something else.
