### ISSUE TITLE
frogbot on scan-pull-request since version >=2.5.2 not possible

### ISSUE THREAD

**Issue by killerquitsche** [jfrog/frogbot#226]
### Describe the bug

In Frogbot version 2.5.2 the [download of a config file](https://github.com/jfrog/frogbot/pull/222/files) was implemented. Since then it is no longer possible for us to run frogbot in our pipeline, because it no longer uses the environment variables and always looks for this config file.
In the code of the merge request you can see that normally there should be a fallback to the environment variables if no config file is given. In the documentation it is not described where this configuration file comes from, how to generate it or how the config should look like. Could you add documentation for this?

### Current behavior

`08:05:33 [Error] GET https://gitlab.blub.de/api/v4/projects/project/my-service/repository/files/.frogbot/frogbot-config.yml: 404 {message: 404 File Not Found}`

### Reproduction steps

Set the frogbot version to 2.5.2.
Run frogbot `scan-pull-request`

### Expected behavior

If no configuration file is specified, the environment variables set in gitlab-ci.yml should be used.

### JFrog Frogbot version

2.5.2

### Package manager info

Maven (pom.xml)

### Git provider

GitLab

### JFrog Frogbot configuration yaml file

no response

### Operating system type and version

CIS Ubuntu 20 04 LTS

### JFrog Xray version

3.62.4

**Comment by omerzi** [comment]
Hey @killerquitsche, thanks for reporting this issue. You can find the documentation here: 
https://github.com/jfrog/frogbot/blob/master/docs/frogbot-config.md

About this bug, we will check it out and I'll update once there is progress.

**Comment by omerzi** [comment]
@killerquitsche, can you add the full debug logs?
To enable debug mode please set the JFROG_CLI_LOG_LEVEL=DEBUG environment variable.

**Comment by omerzi** [comment]
@killerquitsche seems like we found the root cause, we will soon fix it and I'll keep you posted.

**Comment by omerzi** [comment]
Hey @killerquitsche, [v2.5.4 is released](https://github.com/jfrog/frogbot/releases/tag/v2.5.4). Please let me know if it works for you, thanks!

**Comment by killerquitsche** [comment]
Hi @omerzi 
thank you for the super fast fix.
I have just tested frogbot 2.5.4 in our pipeline. Everything is working again without any problems.

Thanks a lot!
