### ISSUE TITLE
Git clone not using `JF_GIT_API_ENDPOINT`

### ISSUE THREAD

**Issue by joachimBurket** [jfrog/frogbot#255]
### Describe the bug

We have an on-prem GitLab instance running on "gitlab.ourdomain".
When running the command `scan-and-fix-repos` and vulnerabilities are found, frogbot tries to clone the repository without using `JF_GIT_API_ENDPOINT` to construct the clone URL

### Current behavior

Here is the output of our CI:

```
$ env | grep "JF"
JF_URL=https://jfrog.ourdomain
JF_GIT_OWNER=my-group/test
JF_GIT_REPO=demo-app
JF_GIT_API_ENDPOINT=https://gitlab.ourdomain
JF_GIT_TOKEN=[MASKED]
JF_USER=gitlab
JF_GIT_PROVIDER=gitlab
JF_PASSWORD=[MASKED]
JF_GIT_BASE_BRANCH=main

$ frogbot scan-and-fix-repos
09:49:52 [Debug] Downloading frogbot-config.yml from target my-group/test / demo-app / main
09:49:53 [Info] Running Frogbot "scan-and-fix-repos" command 
09:49:53 [Debug] Usage Report: Sending info...
09:49:53 [Debug] Sending HTTP GET request to: https://jfrog.ourdomain/artifactory/api/system/version
09:49:53 [Debug] Created temp working directory:  /tmp/jfrog.cli.temp.-1678265393-192215614
09:49:53 [Debug] Downloading my-group/test/demo-app , branch: main to: /tmp/jfrog.cli.temp.-1678265393-192215614
09:49:53 [Debug] Artifactory response: 200 
09:49:53 [Debug] JFrog Artifactory version is: 7.41.13
09:49:53 [Debug] Sending HTTP POST request to: https://jfrog.ourdomain/artifactory/api/system/usage
09:49:53 [Debug] Usage Report: Artifactory response: 200 
09:49:53 [Debug] Usage Report: Usage info sent successfully.
09:49:53 [Info] demo-app downloaded successfully, starting with repository extraction
09:49:53 [Info] extracted repository successfully
09:49:53 [Debug] Repository download completed
09:49:53 [Info] Auditing project: /tmp/jfrog.cli.temp.-1678265393-192215614
09:49:53 [Info] Detected: poetry.
09:49:53 [Debug] Running "poetry install"
09:50:08 [Debug] Sending HTTP GET request to: https://jfrog.ourdomain/xray/api/v1/system/version
09:50:08 [Info] JFrog Xray version is: 3.57.6
09:50:08 [Info] Scanning module ...
09:50:08 [Debug] Sending HTTP POST request to: https://jfrog.ourdomain/xray/api/v1/scan/graph?scan_type=dependency
09:50:09 [Info] Waiting for scan to complete...
09:50:09 [Debug] Sending HTTP GET request to: https://jfrog.ourdomain/xray/api/v1/scan/graph/b8066348-8c14-492e-7fb0-13d21a2f3fd7?include_vulnerabilities=true
09:50:09 [Debug] Get Dependencies Scan results... (Attempt 1)
09:50:14 [Debug] Sending HTTP GET request to: https://jfrog.ourdomain/xray/api/v1/scan/graph/b8066348-8c14-492e-7fb0-13d21a2f3fd7?include_vulnerabilities=true
09:50:14 [Info] Xray scan completed
09:50:14 [Debug] Upload Scan to GitLab is currently unsupported.
09:50:14 [Info] Found 2 vulnerable dependencies with fix versions
09:50:14 [Debug] Created temp working directory: /tmp/jfrog.cli.temp.-1678265414-3030771806
09:50:14 [Info] Cloning repository with these details:
Clone url: https://gitlab.com/my-group/test/demo-app.git remote name: origin, branch: refs/heads/main
09:50:14 [Error] repository demo-app returned the following error: 
'git clone main from https://gitlab.com/my-group/test/demo-app.git' failed with error: authentication required
```

### Reproduction steps

Set the environment variable `JF_GIT_API_ENDPOINT` to gitlab instance URL, and run the command `scan-and-fix-repos` on a repository with vulnerabilities.

### Expected behavior

The repo 'clone_url' should be 'https://gitlab.ourdomain/my-group/test/demo-app.git' instead of 'https://gitlab.com/my-group/test/demo-app.git'

### JFrog Frogbot version

2.5.9

### Package manager info

poetry - pyproject.toml

### Git provider

GitLab

### JFrog Frogbot configuration yaml file

```yaml
- params:
    # Git parameters
    git:
      # [Mandatory]
      # Name of the git repository to scan
      repoName: demo-app

      # [Mandatory]
      # List of branches to scan
      branches:
        - main
```

### Operating system type and version

RHEL 8.6

### JFrog Xray version

3.57.6

**Comment by omerzi** [comment]
Hey @joachimBurket, Thank you for reporting this issue.
Did you use the GitLab template as documented [here](https://github.com/jfrog/frogbot/blob/master/docs/install-gitlab.md)?

**Comment by joachimBurket** [comment]
Hi @omerzi. 
No, because I want to use frogbot "Scanning repositories and fixing issues" feature instead of the "Scan pull requests when they are opened" one, but I couldn't find documentation on this for GitLab.

So my idea was to run frogbot periodically with a scheduled pipeline from a "management" repository. This repo has the following `.gitlab-ci.yml`:

```yaml
# our frogbot image from our private repo
image: docker.jfrog.ourdomain/frogbot:latest

frogbot-scan:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - .gitlab-ci.yml
  variables:
    JF_GIT_OWNER: my-group/test
    JF_GIT_REPO: demo-app
    JF_GIT_BASE_BRANCH: main
    JFROG_CLI_LOG_LEVEL: DEBUG
    
  script:
    - env | grep "JF_"
    # scan and fix repos
    - frogbot scan-and-fix-repos
```

And it has the following variables defined in the project's CICD variables:
* JF_GIT_API_ENDPOINT
* JF_GIT_PROVIDER
* JF_GIT_TOKEN
* JF_USER
* JF_PASSWORD
* JF_URL

**Comment by omerzi** [comment]
We recommend using `create-fix-pull-request` in GitLab, instead of `scan-and-fix-repos` since it is more suitable for CI servers that are external to the source code, like GitHub and Jenkins.

`create-fix-pull-request` will be triggered in every new commit to the selected branch, and will suggest fixing a pull request if any vulnerabilities are detected. It is a part of the template [here](https://github.com/jfrog/frogbot/blob/master/docs/install-gitlab.md), and if you wish to remove the `scan-pull-request` part, you definitely can do so, and use only the `create-fix-pull-request`. 

However, you did find something that we need to fix for such situations, and we are working on a patch. We would also be happy to hear your feedback if anything in our documentation is unclear or misleading. We are happy to help you with anything else you may need until you are satisfied with Frogbot.

**Comment by joachimBurket** [comment]
Thanks for your recommendation. We want to use both scenarios. 

The scanning pull request part would be used for the projects we are working on.

But we also have some projects on which we are not working regularly. This is why we would want to have the `scan-and-fix-repos` running once a day on a set of repositories, and creating pull requests when projects have vulnerabilities so that we can patch them (a bit like dependabot is doing on github).

Regarding frogbot documentation, I would suggest you add a config example for this second scenario for gitlab if you think more users would be interested in this use case.

**Comment by omerzi** [comment]
Thank you for the suggestion, @joachimBurket. We'll take it into account. 
As for the issue, we'll release a patch in the next couple of days and I'll keep you posted.

**Comment by omerzi** [comment]
Hey @joachimBurket, Frogbot v2.6.0 has been released with a fix.  I would appreciate it if you can let me know if it works for you. Thanks!

**Comment by joachimBurket** [comment]
Hi @omerzi, thanks for the quick fix! The MR are now created on GitLab :)
