### ISSUE TITLE
Allow to configure the commit messages style

### ISSUE THREAD

**Issue by joachimBurket** [jfrog/frogbot#263]
**Is your feature request related to a problem? Please describe.**
Some of our project use the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) message style. When frogbot creates a MR, the commits don't follow this convention.

**Describe the solution you'd like to see**
Allowing the user to enable a certain commits style in the `frogbot-config.yml`, or to configure the commit messages prefix (e.g. `fix(deps):`)

**Describe alternatives you've considered**
Manually editing the commit message when merging the MR.

**Comment by jghal** [comment]
we're in a similar situation, using [semantic-release](https://github.com/semantic-release/semantic-release#readme) in our pipelines so we have pre-receive hook that checks commits against this regex

`^(Notes added by \'git notes add\')|(\s*(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(.*):((\s)\S*)(\n*.*)*)|(Merge (.*\s*)*)|(Initial commit$)`

**Comment by EyalDelarea** [comment]
Hey @joachimBurket and @jghal 

We've just released a new version with new custom template for commit messages, branches and PRs.
You can now edit theses templates inside the frogbot-config.yml file
Here is an example:

```
params:
    git:
      repoName: repo-name

      branches:
        - master

      branchNameTemplate: "frogbot-${IMPACTED_PACKAGE}-${BRANCH_NAME_HASH}"

      commitMessageTemplate: "Upgrade ${IMPACTED_PACKAGE} to ${FIX_VERSION}"

      pullRequestTitleTemplate: "[🐸 Frogbot] Upgrade ${IMPACTED_PACKAGE} to to ${FIX_VERSION}"

```
Let us know if it solved your issue.

**Comment by jghal** [comment]
will check it out and report back, might be later this week.

**Comment by eyalbe4** [comment]
@joachimBurket and @jghal -
The documentation is now up to date with the relevant workflow variables for controlling the formats of the branch name, commit message and pull request title.
Looking forward to your feedback.

**Comment by jghal** [comment]
I created a _.frogbot/frogbot-config.yml_ file in my repo but it doesn't seem to be working. 

```yaml
---
- params:
    git:
      repoName: mygroup/myproject
      branches:
        - master
      commitMessageTemplate: "chore(deps): Upgrade ${IMPACTED_PACKAGE} to ${FIX_VERSION}"
```

Should the `repoName` value be the whole full project name with namespace, or just the project name? For example with https://gitlab.com/gitlab-org/cli would I put `gitlab-org/cli` or just `cli`? And what frogbot commands does `git.branches` apply to? For example I notice that with this file pushed on a branch named _xray_ with an open MR targeting _master_ then the `scan-pull-request` command runs correctly in that pipeline. I'm still testing `frogbot create-fix-pull-requests` locally, and when I run it (have tried with both the _xray_ and _master_ checked out) the commits fail like this

```shell
11:34:59 [🔵Info] Running git checkout to base branch: master
11:34:59 [🔵Info] -----------------------------------------------------------------
11:34:59 [🔵Info] Start fixing github.com/docker/docker with 19.03.15
11:34:59 [🔵Info] Creating branch frogbot-github.com/docker/docker-94eadfe7d1d548b6620c17280f577fa6 ...
11:35:00 [Debug] Running 'go get github.com/docker/docker@v19.03.15'
11:35:00 [🔵Info] Checking if there are changes to commit
11:35:00 [🔵Info] Running git add all and commit...
11:35:00 [🔵Info] Pushing fix branch: frogbot-github.com/docker/docker-94eadfe7d1d548b6620c17280f577fa6 ...
11:35:02 [🟠Warn] failed while creating a fixing pull request for: github.com/docker/docker with version: 19.03.15 with error: 
git push failed with error: command error on refs/heads/frogbot-github.com/docker/docker-94eadfe7d1d548b6620c17280f577fa6: pre-receive hook declined
```

I've tested an example commit message against my configured regex [here](https://regex101.com/) and it does match.

So I'm wondering if I have something wrong in my frogbot-config.yaml file.

**Comment by eyalbe4** [comment]
@jghal,
The `repoName` value shouldn't include the project or organization name. It should include the repository name only. The project name should be set as the value of the `JF_GIT_OWNER` variable in your GitLab job. See the [Setup Guide](https://github.com/jfrog/frogbot/blob/master/docs/install-gitlab.md) for more information.
Also ensure that the `frogbot-config.yml` is pushed to your target branch. Frogbot attempts to look for it there. 
In addition, see that there isn't a restriction on the branch names. If there is, then also set the variable for the branch name template. 
Please let us know in case you still encounter challenges. We'll assist you overcoming them. We'd also love to hear your confirmation that all works for you as expected.

**Comment by jghal** [comment]
> The `repoName` value shouldn't include the project or organization name. It should include the repository name only. The project name should be set as the value of the `JF_GIT_OWNER` variable in your GitLab job.

I'm not sure I follow. Using the same example of https://gitlab.com/gitlab-org/cli, wouldn't my `JF_GIT_OWNER` be **gitlab-org** (the setup guide link defaults it to `$CI_PROJECT_NAMESPACE`), which is a _group_ path? What is the "repository name" if not the [GitLab] project name (ie **cli**)? Do the `JF_*` environment variables override the values in _frogbot-config.yml_?

> Also ensure that the `frogbot-config.yml` is pushed to your target branch

This appears to have been my main issue. I was setting `JF_GIT_BASE_BRANCH=master` but the file has not yet been merged to master. When I changed that to `JF_GIT_BASE_BRACH=xray`, which is where the file does exist in the repository on gitlab.com, then it started pushing fix branches and opening MRs. However, it appears to be creating branches overzealously. For example this indirect dependency

```shell
15:19:51 [🔵Info] -----------------------------------------------------------------
15:19:51 [🔵Info] Start fixing golang.org/x/crypto with 0.1.0
15:19:52 [🔵Info] Creating branch frogbot-golang.org/x/crypto-c19a9f511e045e1400525e6739ad5e42 ...
15:19:52 [🟠Warn] failed while fixing golang.org/x/crypto with version: 0.1.0 with error: 
Since dependecy 'golang.org/x/crypto' is indirect (transitive) its fix is skipped
15:19:52 [🔵Info] Running git checkout to base branch: master
```

In my project on GitLab, I see a this golang.org/x/crypto branch was pushed with no commits, so a pipeline for this branch was triggered even though there is not only no MR for it, but it has no changes to build/test. Same for this other example, except it seems to be a direct dependency which Xray returned an invalid fixed version for.

```shell
15:19:52 [🔵Info] -----------------------------------------------------------------
15:19:52 [🔵Info] Start fixing github.com/golang/go with 1.19.8
15:19:52 [🔵Info] Creating branch frogbot-github.com/golang/go-6f2a07810c084eeb20bf8674dc2fc231 ...
15:19:52 [Debug] Running 'go get github.com/golang/go@v1.19.8'
15:20:02 [🟠Warn] failed while fixing github.com/golang/go with version: 1.19.8 with error: 
go get github.com/golang/go@v1.19.8 command failed: exit status 1
go: github.com/golang/go@v1.19.8: invalid version: unknown revision v1.19.8
15:20:02 [🔵Info] Running git checkout to base branch: master
```

**Comment by EyalDelarea** [comment]
Hey @jghal,

> I'm not sure I follow. Using the same example of https://gitlab.com/gitlab-org/cli, wouldn't my `JF_GIT_OWNER` be **gitlab-org** (the setup guide link defaults it to `$CI_PROJECT_NAMESPACE`), which is a _group_ path? What is the "repository name" if not the [GitLab] project name (ie **cli**)
>
Please notice that in the `frogbot-config.yml` you do not need to setup `JF_GIT_OWNER` variable
But if you are using a config file, the `repoName` variable  should be **cli**.


>? Do the `JF_*` environment variables override the values in _frogbot-config.yml_?
> 

No, the `frogbot config.yml` file is optional which means that if you use it, we prioritize those variables.


> In my project on GitLab, I see a this golang.org/x/crypto branch was pushed with no commits, so a pipeline for this branch was triggered even though there is not only no MR for it, but it has no changes to build/test. Same for this other example, except it seems to be a direct dependency which Xray returned an invalid fixed version for.
> 
> ```shell
> 15:19:52 [🔵Info] -----------------------------------------------------------------
> 15:19:52 [🔵Info] Start fixing github.com/golang/go with 1.19.8
> 15:19:52 [🔵Info] Creating branch frogbot-github.com/golang/go-6f2a07810c084eeb20bf8674dc2fc231 ...
> 15:19:52 [Debug] Running 'go get github.com/golang/go@v1.19.8'
> 15:20:02 [🟠Warn] failed while fixing github.com/golang/go with version: 1.19.8 with error: 
> go get github.com/golang/go@v1.19.8 command failed: exit status 1
> go: github.com/golang/go@v1.19.8: invalid version: unknown revision v1.19.8
> 15:20:02 [🔵Info] Running git checkout to base branch: master
> ```

This is possible bug that we will look into, we'll make sure to not push redundant branches. Thank you for letting us notice!


**To summerize i would like to suggest to following option:**
If your only goal is to set up commit template you can do that by the following options:

1. set up `JF_COMMIT_MESSAGE_TEMPLATE ` directly in your `frogbot-scan.gitlab-ci.yml` file. ( and delete the `frogbot-config.yml` from your repo.
2. set up frogbot-config.yml file which will look like this:
```
- params:
    git:
      repoName: cli
      branches:
        - master
      commitMessageTemplate: "chore(deps): Upgrade ${IMPACTED_PACKAGE} to ${FIX_VERSION}"
```

Please let us know if you succeeded configuring custom commit template, In case you didn't please share with us if you used `frogbot-config.yml` or `frogbot-scan.gitlab-ci.yml` and share the respectful file so we'll have better understanding how to help.
