### ISSUE TITLE
Add details about which vulnerabilities the Merge Request is fixing

### ISSUE THREAD

**Issue by joachimBurket** [jfrog/frogbot#264]
**Is your feature request related to a problem? Please describe.**
When Frogbot creates a Merge Request to fix vulnerable dependencies, it only says "Upgrade <depName> to <version>" and a link to Frogbot readme.

**Describe the solution you'd like to see**
It would be great to have a link to which CVE is fixed by the Merge Request in the description (and eventually also the vulnerability severity).

This would allow us to have a better idea how urgent the MR is, and also to retroactively view which CVE were fixed in our repositories.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by eyalbe4** [comment]
Thanks for raising @joachimBurket!
We're definately going to implement this.
