### ISSUE TITLE
lodash 4.17.21	showing as Critical but Github advisory shows Low severiy

### ISSUE THREAD

**Issue by miguelfmbarao** [jfrog/frogbot#360]
### Describe the bug

Frogbot severity is not matching Github advisory severity according to https://github.com/advisories/GHSA-8p5q-j9m2-g8wr

### Current behavior

lodash 4.17.21 has Critical severity on Frogbot scan

### Expected behavior

Low severity as the CVE is Withdrawn according to https://github.com/advisories/GHSA-8p5q-j9m2-g8wr not being a security issue

### JFrog Frogbot version

2.8.8

### Package manager info

package.json

### Git provider

GitHub

### Operating system type and version

Microsoft Windows Server 2022 10.0.20348 Datacenter

**Comment by omerzi** [comment]
Hi @miguelfmbarao, thank you for reporting this issue.

I have attempted to reproduce the problem, but I was unable to encounter the same issue. Frogbot did not report any vulnerabilities in the lodash package version 4.17.21.

Could you kindly provide additional information, such as debug logs? To enable debug logs, please set the JFROG_CLI_LOG_LEVEL environment variable to DEBUG.

Your cooperation is greatly appreciated.

**Comment by miguelfmbarao** [comment]
Hi @omerzi here is a screenshot: 
![image](https://github.com/jfrog/frogbot/assets/110819945/9f271f0e-a164-4769-b9c6-ccda7be5f95f)
So yes lodash is not reported as direct dependency because its not used directly, but its impacted dependency for some well known Angular packages

**Comment by omerzi** [comment]
Thanks @miguelfmbarao, I will look into it and will update you with additional information ASAP.

**Comment by miguelfmbarao** [comment]
Closing, its no longer happening on Frogbot version: 2.9.1.  Best regards
