### ISSUE TITLE
Add an option to avoid posting "No issues" banners to PR comments

### ISSUE THREAD

**Issue by ilya-k-1** [jfrog/frogbot#361]
"No issues" banners add a lot of spam to our PR conversation histories, for very little gain. 

We would like to have an option to post to PR conversations only in the case a vulnerability was detected.

**Comment by omerzi** [comment]
Hi @ilya-k-1 , the issue has been fixed in Frogbot v2.11.3. Thank you once again for reporting this issue to us. Please let us know if you have any further questions.
