### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference   [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xdcf2fd]

### ISSUE THREAD

**Issue by Rushekesh** [jfrog/frogbot#390]
Getting below error while scanning github resusable workflow using frogbot
`
![image](https://github.com/jfrog/frogbot/assets/22794078/a1fd35c5-6e4c-4f46-a8c4-3320b0430766)
`

**Comment by eyalbe4** [comment]
@Rushekesh,
What is the reason you closed this issue?

**Comment by Rushekesh** [comment]
I opened another ticket. Please help me if you have any insight on this
issue.
https://github.com/jfrog/frogbot/issues/391
