### ISSUE TITLE
avoid frogbot from overwriting the comment section as part of every scan

### ISSUE THREAD

**Issue by nx2804** [jfrog/frogbot#511]
Hi Team,

I wanted to know is there any variable to avoid frogbot being overwriting the comments in PR as part of every execution?

**Comment by eyalbe4** [comment]
There isn't currently @nx2804.
Would you have used such a variable if we added it? Will you be able to share more info about the requirement and why such option be useful for you?

**Comment by nx2804** [comment]
any update on this please

**Comment by eyalbe4** [comment]
@nx2804,
Thank you for sharing this requirement. 
I believe we can add a new variable that to make Frogbot skip the deletion of old comments added by Frogbot on PRs.
Let us update this issue once we add this functionality.

**Comment by nx2804** [comment]
Sure thanks it would be great if you can make this available asap

**Comment by nx2804** [comment]
Any update on this request

**Comment by sverdlov93** [comment]
Hi @nx2804,
Could you please provide further details about your Git provider and CI server setup? Additionally, could you clarify why the frogbot is triggered for every pipeline? Ideally, we'd like frogbot to be triggered only when a new commit is made to the pull request.
Thank you!

**Comment by nx2804** [comment]
Azure repos and azure devops pipeline
We have a consolidated pr which has all individual build validation ci
triggered together

**Comment by nx2804** [comment]
any updates on this please

**Comment by attiasas** [comment]
Hi @nx2804, I'm working on this feature and it will soon be available.
you can follow: https://github.com/jfrog/frogbot/pull/537

**Comment by attiasas** [comment]
Hi @nx2804,

We are pleased to announce the release of Frogbot v2.17.0, which incorporates this feature.

To enable this feature, you can either set the environment variable as follows:
```
JF_AVOID_PREVIOUS_PR_COMMENTS_DELETION: "TRUE"
```
or update your Frogbot configuration by adding the scan parameter:


```
avoidPreviousPrCommentsDeletion: true
```

Please don't hesitate to reach out if you encounter any difficulties or have any questions.

**Comment by nx2804** [comment]
Hi

Thanks let me test and get back to you

**Comment by nx2804** [comment]
Hi

This has solved the overwriting of comment problem but with latest version
of frogbot  when i set JF_INCLUDE_ALL_VULNERABILITIES: TRUE it is not
displaying the vulnerabilities . Instead it always prints that the PR has
no issues

**Comment by attiasas** [comment]
Hi @nx2804,

I noticed that the issue at https://github.com/jfrog/frogbot/issues/541, which you opened after this current issue, has been marked as resolved. Could you please verify this? Are there any other issues or concerns that need attention?

**Comment by nx2804** [comment]
Currently frogbot is reporting issues in pull request but that doesn’t
display which pipeline has this issue during pull request scan


Say for example I have multiple pipelines included in build validations in
PR, the scan should report which pipeline has this issues

**Comment by omerzi** [comment]
Hi @nx2804, we have recently received a similar feature request, which you can find here: https://github.com/jfrog/frogbot/issues/550. We are initiating the implementation of the new feature that will enable the addition of a custom header to pull request comments, such as the relevant pipeline, through an environment variable. I will keep you informed of our progress and notify you once Frogbot is released with this new feature. Thank you.

**Comment by nx2804** [comment]
Sure will check and keep you posted

**Comment by nx2804** [comment]
it works thanks
