### ISSUE TITLE
I'm running Enterprise Plus, why does it says "isn't enabled on your system"

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/frogbot#536]
I'm running Enterprise Plus, the most expensive available tier. Yet, the pull request annotation says: 

![image](https://github.com/jfrog/frogbot/assets/30481051/c6f83cfc-a06b-4119-8138-d14ae08507ad)

Can someone explain how to make this work without this error message?

**Comment by eyalbe4** [comment]
@EvertonSA,
Could it be that your subscription doesn't include the **Advanced Security** package? I recommend approaching your JFrog account contact or JFrog Support for assistance with this. Please let us know if you need further assistance and we'd be happy to assist.

**Comment by EvertonSA** [comment]
that could be the case, will check internally. thanks!
