### ISSUE TITLE
JF_INCLUDE_ALL_VULNERABILITIES: TRUE it is not displaying the vulnerabilities . Instead it always prints that the PR has no issues

### ISSUE THREAD

**Issue by nx2804** [jfrog/frogbot#541]
### Describe the bug

JF_INCLUDE_ALL_VULNERABILITIES: TRUE it is not displaying the vulnerabilities . Instead it always prints that the PR has no issues

### Current behavior

Always the PR  validations are successful

### JFrog Frogbot version

latest

### Package manager info

pom.xml

### Git provider

GitHub

### JFrog Frogbot configuration yaml file

steps:
# included comment
- task: CmdLine@2
  condition: eq(variables['Build.Reason'], 'PullRequest')
  displayName: 'Download and Run Frogbot Scan'
  env:
    JF_GIT_PULL_REQUEST_ID: $(System.PullRequest.PullRequestId)
    JF_GIT_BASE_BRANCH: $(System.PullRequest.TargetBranch)
    JF_GIT_PROJECT: $(System.TeamProject)
    JF_GIT_API_ENDPOINT: $(System.CollectionUri)
    JF_GIT_TOKEN: $(access-token-pat)
    JF_VULN_CONTEXTUAL_ANALYSIS: TRUE
    JF_URL: $(artifactoryurl)
    JF_ACCESS_TOKEN: $(jfrog-identity-token)
    JFROG_CLI_LOG_LEVEL: "DEBUG"
    JF_GIT_OWNER: "KLA-GPG"
    JF_AVOID_PREVIOUS_PR_COMMENTS_DELETION: FALSE
    JF_GIT_REPO: "virgo"
    JF_RELEASES_REPO: ""
    JF_GIT_PROVIDER: "azureRepos"
    JF_FAIL: TRUE
    JF_INCLUDE_ALL_VULNERABILITIES: TRUE
    JF_WORKING_DIR: ${{ parameters.componentName }}
  inputs:
    script: |
      getFrogbotScriptPath=$(if [ -z "$JF_RELEASES_REPO" ]; then echo "https://releases.jfrog.io"; else echo "${JF_URL}/artifactory/${JF_RELEASES_REPO}"; fi)
      curl -fLg "$getFrogbotScriptPath/artifactory/frogbot/v2/[RELEASE]/getFrogbot.sh" | sh
      ./frogbot spr
      #./frogbot scan-and-fix-repos $(Build.SourceBranch)

### Operating system type and version

linux

**Comment by attiasas** [comment]
Hi @nx2804, thank you for bringing this issue to our attention.

Could you please provide additional details regarding this issue? If you are not using this parameter, does the scan discover issues, and it only passes when this parameter is enabled?

Additionally, it would be helpful if you could provide the run logs or a link to the repository/PR that you attempted to scan. This information will assist us in investigating and resolving the problem more effectively.

**Comment by nx2804** [comment]
During PR validation when we include  JF_INCLUDE_ALL_VULNERABILITIES: TRUE
it will scan and report all the code and comment it pr section. But right
now with latest version of frogbot even after enabling this variable it
still gives me a message as  all good with the code no vulnerabilities
found. Can this be fixed please

[image: image.png]

**Comment by attiasas** [comment]
Hi @nx2804, 

You've mentioned that you're aware of vulnerabilities in your repository, primarily because you've been using this variable in your PR validations. However, with the latest versions, it seems that these vulnerabilities are no longer visible. Is that accurate?

if you scan your repository (scan-and-fix-repos) can it detect these vulnerabilities?

I've made attempts to replicate this issue on my end, and it seems to be functioning correctly, as it detects and comments on all the expected issues, regardless of whether the parameter is enabled or not. To help me investigate further, could you provide the steps to reproduce this issue (maybe a test repository that has this issue), along with any relevant logs? Your input will be invaluable in resolving this matter.

**Comment by nx2804** [comment]
yep i am trying to perform the same thing which you have mentioned in first
point.

add the following code in my pipeline

steps:
# included comment
- task: ***@***.***
  condition: eq(variables['Build.Reason'], 'PullRequest')
  displayName: 'Download and Run Frogbot Scan'
  env:
    JF_GIT_PULL_REQUEST_ID: $(System.PullRequest.PullRequestId)
    JF_GIT_BASE_BRANCH: $(System.PullRequest.TargetBranch)
    JF_GIT_PROJECT: $(System.TeamProject)
    JF_GIT_API_ENDPOINT: $(System.CollectionUri)
    JF_GIT_TOKEN: $(access-token-pat)
    JF_VULN_CONTEXTUAL_ANALYSIS: TRUE
    JF_URL: $(artifactoryurl)
    JF_ACCESS_TOKEN: $(jfrog-identity-token)
    JFROG_CLI_LOG_LEVEL: "DEBUG"
    JF_GIT_OWNER: "KLA-GPG"
    JF_AVOID_PREVIOUS_PR_COMMENTS_DELETION: FALSE
    JF_GIT_REPO: "virgo"
    JF_RELEASES_REPO: ""
    JF_GIT_PROVIDER: "azureRepos"
    JF_FAIL: TRUE
    JF_INCLUDE_ALL_VULNERABILITIES: TRUE
    JF_WORKING_DIR: ${{ parameters.componentName }}
  inputs:
    script: |
      getFrogbotScriptPath=$(if [ -z "$JF_RELEASES_REPO" ]; then echo "
https://releases.jfrog.io
"; else echo "${JF_URL}/artifactory/${JF_RELEASES_REPO}"; fi)
      curl -fLg
"$getFrogbotScriptPath/artifactory/frogbot/v2/[RELEASE]/getFrogbot.sh"
| sh
      ./frogbot spr



During PR scan it doesnt report any errors. Earlier it used to report all
the issues

**Comment by nx2804** [comment]
This is working now
