### ISSUE TITLE
How to get PR's created in Azure DevOps

### ISSUE THREAD

**Issue by jashan05** [jfrog/frogbot#562]
Hello Team,

I am using the given instructions, and able to run a scan after downloading the Frogbot. Pipeline based on the shared template gets executed successfully but i dont see any PR's generated. What can be the issue. Logs from pipeline are as per below:

``` 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 23  2395   23   555    0     0    787      0  0:00:03 --:--:--  0:00:03   787
100  2395  100  2395    0     0   3397      0 --:--:-- --:--:-- --:--:--  3392
Downloading the latest version of Frogbot...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 30 25.5M   30 7902k    0     0  4375k      0  0:00:05  0:00:01  0:00:04 8232k
100 25.5M  100 25.5M    0     0  11.7M      0  0:00:02  0:00:02 --:--:-- 19.1M
Frogbot downloaded successfully!
15:18:16 [Info] Frogbot version: 2.18.0
15:18:16 [Info] Running Frogbot "scan-repository" command
15:18:17 [Info] Running SCA scan for vulnerable dependencies...
15:18:17 [Info] Detected: npm.
15:18:17 [Info] Calculating npm dependencies...
15:18:26 [Warn] Ecosystem-Usage(Attempt 1) - Failure occurred while sending POST request to https://usage-ecosystem.jfrog.io/api/usage/report: Post "[https://usage-ecosystem.jfrog.io/api/usage/report"](https://usage-ecosystem.jfrog.io/api/usage/report%22): net/http: TLS handshake timeout
15:18:26 [Info] Ecosystem-Usage executor timeout after 0 attempts with 0 milliseconds wait intervals
15:18:27 [Info] Scanning 591 npm dependencies...
15:18:28 [Info] Waiting for scan to complete on JFrog Xray...
15:18:58 [Info] Xray scan completed
15:18:58 [Info] Frogbot "scan-repository" command finished successfully
```

**Comment by attiasas** [comment]
Hi @jashan05,

Thank you for reporting this issue. Could you please provide more information about this issue? Kindly attach the log with 'debug' information by adding the environment variable 'JFROG_CLI_LOG_LEVEL': 'DEBUG'.

In Azure Repos, we only create pull requests for dependency issues (CVE) that have a fix in a released version. Are you aware of a security issue that we should have discovered and opened a pull request for? If so, could you provide the steps to replicate this issue?

Thank you for your assistance.

**Comment by jashan05** [comment]
Hello @attiasas ,

Thanks for quick response !
By enabling DEBUG mode i see it is skipping the indirect dependency update. Is there any documentation which i can refer for more information on the behaviour of Frogbot.

 Please see the logs below:

``` 
10:53:10 [Info] Xray scan completed
10:53:10 [Debug] Frogbot will attempt to resolve the following vulnerable dependencies:
 tough-cookie,
formidable
10:53:10 [Debug] Attempting to fix tough-cookie with 4.1.3
10:53:10 [Debug] Creating branch frogbot-tough-cookie-55a2094db87e0b506cfe7698b7536175 ...
10:53:10 [Debug] tough-cookie is an indirect dependency that will not be updated to version 4.1.3.
Fixing indirect dependencies can potentially cause conflicts with other dependencies that depend on the previous version.
Frogbot skips this to avoid potential incompatibilities and breaking changes.
10:53:10 [Debug] Running git checkout to branch: main
10:53:10 [Debug] Attempting to fix formidable with 3.2.4
10:53:10 [Debug] Creating branch frogbot-formidable-69bab9618eba86d7d6a53b9c9b97213f ...
10:53:10 [Debug] **_formidable is an indirect dependency that will not be updated to version 3.2.4.
Fixing indirect dependencies can potentially cause conflicts with other dependencies that depend on the previous version.
Frogbot skips this to avoid potential incompatibilities and breaking changes._**
10:53:10 [Debug] Running git checkout to branch: main
10:53:10 [Info] Frogbot "scan-repository" command finished successfully

```
Also another question, can it also create PR's if there are new versions detected in case the current used version doesnt have any vulnerabilities.


Best Regards
Jashan

**Comment by eyalbe4** [comment]
@jashan05,

The Frogbot documentation currently doesn't describe in detail the strategies used for fixing vulnerable depedencies. Those strategies aren't the same across all package managers supported by Frogbot, and we're also refining them over time to produce the best outcome.

As for your second question, Frogbot currently focuses on fixing security vulnerabilities only, but allowing upgrades from versions that aren't vulnerable is something that we're considering for the future.

Please feel free to reach out if you have any more questions or if you need further assistance.

**Comment by jashan05** [comment]
Thanks @eyalbe4 , will keep an eye out from new functionalities. Closing the issue
