### ISSUE TITLE
scan-repository - invalid character '\x1b' looking for beginning of value

### ISSUE THREAD

**Issue by philippe-granet** [jfrog/frogbot#587]
### Describe the bug

I have this error: `invalid character '\x1b' looking for beginning of value` when running `JFROG_CLI_LOG_LEVEL="DEBUG" ./frogbot scan-repository`

### Current behavior

```
...
10:06:55 [Info] Scanning 68 maven dependencies...
10:06:55 [Debug] Sending HTTP GET request to: https://corporate.server/xsc/api/v1/system/version
10:06:55 [Debug] Sending HTTP POST request to: https://corporate.server/xray/api/v1/scan/graph?scan_type=dependency
10:06:57 [Info] Waiting for scan to complete on JFrog Xray...
10:06:57 [Debug] Sending HTTP GET request to: https://corporate.server/xray/api/v1/scan/graph/bf9d6897-b5a7-4a4c-68d9-86700aab225d?include_vulnerabilities=true
10:06:57 [Info] Xray scan completed
10:06:57 [Debug] Frogbot will attempt to resolve the following vulnerable dependencies:
 org.yaml:snakeyaml
10:06:57 [Debug] Attempting to fix org.yaml:snakeyaml with 1.32
10:06:58 [Debug] Creating branch frogbot-org.yaml_snakeyaml-5a87bec8bb1cf3172c29879cebb34eab ...
10:07:01 [Debug] Running git checkout to branch: master
10:07:01 [Error] the following errors occured while fixing vulnerabilities in /home/dev/tmp/jfrog.cli.temp.-1701115606-436159568:
invalid character '\x1b' looking for beginning of value
```

### JFrog Frogbot version

Frogbot version: 2.19.2

### Package manager info

Maven 3.9.5

### Git provider

GitLab

### Operating system type and version

Debian 12

### JFrog Xray version

JFrog Xray version 3.41.4

**Comment by omerzi** [comment]
Hi @philippe-granet, thank you for reporting this issue and for using Frogbot. We will attempt to reproduce it. This error often occurs when using `json.Unmarshal` as we do here: https://github.com/jfrog/frogbot/blob/master/packagehandlers/mavenpackagehandler.go#L249.
Additionally, we'll include a proper error message and log it in the relevant location to facilitate further debugging if necessary.
I'll update you on the progress of this matter as soon as possible, thank you once again.

**Comment by omerzi** [comment]
Hi @philippe-granet, yes, this is an improvement we can make. I'll keep you updated on the progress of the implementation. Thanks for the feedback!

**Comment by omerzi** [comment]
@philippe-granet, Frogbot v2.19.5 has been released with the improvement we discussed. Please let me know if it works for you. Thank you!

**Comment by philippe-granet** [comment]
Yes it's OK, thank you!
