### ISSUE TITLE
Fails to scan custom python packages 

### ISSUE THREAD

**Issue by sharvesh06** [jfrog/frogbot#667]
Frogbot fails when it tries to scan custom python package,
`22:22:44 [Info] Xray scan completed 22:22:53 [Error] the following errors occured while fixing vulnerabilities in '/tmp/jfrog.cli.temp.-1710281552-1494864668': an error occurred while attempting to read the requirements file: open setup.py: no such file or directory`
We have a monorepo and JF_REQUIREMENTS_FILE is set to ""

**Comment by attiasas** [comment]
Hi @sharvesh06,

Thank you for using Frogbot!

How do you typically install your project? Do you have a setup.py file that lists your dependencies? If your dependencies are stored in a different file, such as requirements.txt, you'll need to provide the file name or relative path to the JF_REQUIREMENTS_FILE environment variable. This allows Frogbot to locate your project dependencies and install them accordingly.

Please feel free to reach out if you have any further questions or encounter any issues.

**Comment by eranturgeman** [comment]
Hello @sharvesh06 
Did the answer provided above resolved your issue and I can close the ticket?
If not please feel free to respond here so we can help you fix the issue
