### ISSUE TITLE
Operational Risk Violations in Frogbot PR Scanning

### ISSUE THREAD

**Issue by pru-qmir** [jfrog/frogbot#731]
Frogbot PR Scanning is configured for Security, License, and Operational Risk policies. However, reports only include Security and License violations. Is there support for Operational Risk Violations within Frogbot PR Scanning? Guidance on this matter is appreciated.

**Comment by eranturgeman** [comment]
Hello @pru-qmir, and thank you for using Frogbot!
At the moment, Operational risk reports are only available for ‘jf audit’ and not supported by Frogbot. If you believe this feature would be valuable, please reach out to your Jfrog representative to request it, or submit a feature request directly through GitHub issues
