### ISSUE TITLE
Resolving Pull request comment from frogbot

### ISSUE THREAD

**Issue by build630** [jfrog/frogbot#775]
When we scan the pull request through "frogbot.exe spr", it is adding comment to pull request.

Per branch policies, Active PR comment blocks the completion of PR's and user have to resolve it manually. So, I am checking if there is a way to keep comments as active, only if the PR introduces any vulnerabilities. Otherwise, PR comment should be marked as resolved automatically.

1. Is there a parameter that is capturing if the PR has any issues or not
2. Is there a way to configure/mark the pull request comment as completed, if there are no issues.

**Comment by eyalk007** [comment]
Hello @build630,

Thank you for using Frogbot!

In the next release of Frogbot, we will offer the option to add this flag:
`JF_PR_ADD_SUCCESS_COMMENT`

You can use it like this: `JF_PR_ADD_SUCCESS_COMMENT=false`

This will prevent Frogbot from creating the success comment in your pull requests.
If you have any more questions or need further assistance, please feel free to ask.
