### ISSUE TITLE
Permission denied on gradlew

### ISSUE THREAD

**Issue by mcavey-arch** [jfrog/frogbot#790]
Hi, im attempting to get Frogbot PR scanning working on a Java project in my github organisation - but whilst it detects it is gradlew that is needed, it is failing with permission issues. I have tried using chmod in a previous step to no effect.

Are there any parameters on the frogbot action that are related to this?

Any assistance would be appreciated.

```
10:36:16 [Info] Preforming scans on 1 targets:
  {
    "xray_version": "3.107.11",
    "xsc_version": "1.12.5",
    "jas_entitled": false,
    "command_type": "source_code",
    "start_time": "2024-11-28T10:36:15.248895194Z",
    "multi_scan_id": "9[82](https://github.com/******/actions/runs/12067188167/job/33649617256?pr=22#step:6:83)21207-ad74-11ef-99fe-62877ead494e",
    "targets": [
      {
        "target": "/tmp/jfrog.cli.temp.-1732790175-[86](https://github.com/*******/actions/runs/12067188167/job/33649617256?pr=22#step:6:87)0464753",
        "technology": "gradle",
        "sca_scans": {
          "descriptors": [
            "/tmp/jfrog.cli.temp.-1732790175-860464753/build.gradle"
          ]
        }
      }
    ]
  }
```

```
  Error: 7 [Error] target '/tmp/jfrog.cli.temp.-1732790175-860464753 [gradle]' errors:
  Failed to build dependency tree: failed while building 'gradle' dependency tree:
  error running gradle-dep-tree: fork/exec ./gradlew: permission denied
```

**Comment by stephen-BT** [comment]
I am also experiencing this exact issue on my gradle project.

**Comment by mcavey-arch** [comment]
Got to the bottom of this - gradlew isnt marked as executable in git.

Resolved with:

git update-index --chmod=+x gradlew
git ls-files --stage   (lists all the files - gradlew should now be 00755 rather than 00754)
git add gradlew
git commit -m "Make gradlew 0755 (executable)"

Had to do this through the command line as GitHub desktop did not recognise the change.

This is now working for me.
