### ISSUE TITLE
Frogbot support

### ISSUE THREAD

**Issue by tomer1983** [jfrog/frogbot#808]
Is frogbot able to work with a self host airgap instance of xray ? Or only a saas version ?

I couldn't find any info about that

**Comment by eranturgeman** [comment]
Hello @tomer1983 and thank you for using Frogbot!
Yes, you are able to use Frogbot in a self-hosted airgap environment.
You can find instruction for this here: https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot/setup-frogbot/setup-frogbot-using-github-actions/scan-git-repository-full-template
![Image](https://github.com/user-attachments/assets/071d7a0f-4ff0-4450-8aa1-f144d2504f3d)

In general, follow the instructions in the docs, and create the necessary remote repository as explained.
Then, in the CI defining Frogbot please provide the relative path to the remote repository you created to the JF_RELEASES_REPO env var (to make sure you provide the correct path, you can click on the repo you want to be your proxy and in its 'General' details you will see "Repository Path" field which contains the value you need)
![Image](https://github.com/user-attachments/assets/6150c864-2648-4868-8c42-dc48b4091af0)

If you experience any troubles, don't hesitate to contact us again and reopen the ticket :)
