### ISSUE TITLE
"Server ID <ID>: URL is required" error will be thrown when on Frogbot scan when there is maven.yaml file configured with private registry

### ISSUE THREAD

**Issue by Infinityxx** [jfrog/frogbot#94]
**Describe the bug**
When using the Frogbot scan with Maven project and there is also a .jfrog/projects//maven.yaml file that points to a private registry, the cli-core will try to use the maven.yaml server ID which is not recognized by Github Actions and will lead to error:

Error: 2 [Error] Server ID arti-test: URL is required.

**To Reproduce**
Used the [template](https://github.com/jfrog/frogbot/blob/master/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml)
Add maven.yaml file such as follows:

version: 1
type: maven
resolver:
  serverId: my-saas
  snapshotRepo: libs-snapshots
  releaseRepo: libs-releases
deployer:
  serverId: my-saas
  snapshotRepo: libs-snapshots
  releaseRepo: libs-releases

**Expected behavior**
Frogbot should not throw an error about that.

**Versions**
- Frogbot version: 2.1.2
- JFrog Artifactory version: 7.38.8
- JFrog Xray version: 3.48.2

**Comment by talarian1** [comment]
Hi, @Infinityxx thanks for reporting this issue, and sorry for the inconvenience.
Our plan is to add support for Frogbot resolving dependencies from Artifactory in this Q.
We will make sure the new feature will handle this use case as well, and will keep you up to date.

**Comment by eyalbe4** [comment]
@Infinityxx -
We're trying to come up woith a solution a soon as possible.

**Comment by sverdlov93** [comment]
Hi @Infinityxx
JFrog Frogbot 2.3.3 is released and should fix the above issue.
Looking forward to your feedback on it.
