### ISSUE TITLE
Frogbot scan significantly slow than Xray UI

### ISSUE THREAD

**Issue by jameselderxe** [jfrog/frogbot#96]
Hi,

We are finding that the Frogbot scans are a lot slower than the equivalent scans/reports in the Xray UI. For instance a Frogbot scan takes ~13 minutes and the Xray UI takes ~10-30 seconds for the same artifact.

What resources are recommended and what parameters/options can we tune to improve Frogbot performance please?

Thanks!

**Comment by eyalbe4** [comment]
@jameselderxe,
Which git provider are using? GitHub, GitLab or Bitbucket?

**Comment by jameselderxe** [comment]
Ah sorry i should have said we are using Gitlab, the project is a .NET project and the job script is run in a .NET SDK Docker container.

`frogbot-scan:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        FROGBOT_CMD: "scan-pull-request"
      # Creating fix pull requests will be triggered by any push to the default branch.
      # You can change it to any other branch you want, for example:
      # if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        FROGBOT_CMD: "create-fix-pull-requests"
  variables:
    # [Mandatory only for projects which use npm, pip, pipenv, nuget and dotnet to download their dependencies]
    # The command that installs the project dependencies (e.g "npm i", "nuget restore" or "dotnet restore")
    JF_INSTALL_DEPS_CMD: "dotnet restore $SOLUTION_PATH --source https://artifactory.oneeuronet.com/artifactory/api/nuget/v3/nuget-proxy/"

    # [Mandatory]
    # JFrog platform URL
    JF_URL: https://$ARTIFACTORY_URL

    # [Mandatory if JF_ACCESS_TOKEN is not provided]
    # JFrog user and password with 'read' permissions for Xray
    JF_USER: $ARTIFACTORY_PRO_USERNAME
    JF_PASSWORD: $ARTIFACTORY_PRO_PASSWORD

    # [Mandatory]
    # GitLab accesses token with the following permissions scopes: api, read_api, read_user, read_repository
    JF_GIT_TOKEN: $GITLAB_TOKEN

    # Predefined GitLab variables. There's no need to set them.
    JF_GIT_PROVIDER: gitlab
    JF_GIT_OWNER: $CI_PROJECT_NAMESPACE
    JF_GIT_REPO: $CI_PROJECT_NAME
    JF_GIT_BASE_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    JF_GIT_PULL_REQUEST_ID: $CI_MERGE_REQUEST_IID
    JF_GIT_API_ENDPOINT: https://$GITLAB_URL
    JF_PROJECT: "xemt"
  image:
    name: dotnet/sdk/5.0-alpine:latest
  script:
    - curl -fLg "https://releases.jfrog.io/artifactory/frogbot/v2/[RELEASE]/getFrogbot.sh" | sh
    - ./frogbot ${FROGBOT_CMD}`

**Comment by yahavi** [comment]
@jameselderxe,
Thanks for reporting this issue!
Frogbot detects newly added vulnerabilities in pull requests. To do that, it clones the source and the target branches and runs different Xray scans. The results are the differences between the scans.

We are planning to add a caching mechanism that is supposed to reduce the scan time significantly. This change is expected to take place during the next few weeks.
We'll keep you updated.

**Comment by jameselderxe** [comment]
@yahavi Thank you for the information, is there anything we can do in the meantime to improve performance? The reason I ask is that the slowness makes Frogbot unusable for us and so we can no use it as part of our MR process in it's current form.

Also I would like to see the ability to set a flag in Frogbot to report all vulnerabilities in the source branch vs new vulnerabilities.

I.e. if there was an environment variable pass to Frogbot called say `VULNERABILITIES`, you could set this to either:

- `ALL` - will show all vulnerabilities and scan just the source branch
- `NEW` - will show only vulnerabilities added by the source branch and will need to scan both source and destination branch

**Comment by eyalbe4** [comment]
@jameselderxe,
We expect that after introducing the option of showing all vulnerabilities, and not just new ones, when using it we'll see a 50% performance improvement. I think that we can try and introduce this functionality quickly, even before the new cache @yahavi mentioned above.

**Comment by omerzi** [comment]
Hey @jameselderxe, thank you for opening this issue. The [Frogbot v2.1.3](https://github.com/jfrog/frogbot/releases/tag/v2.1.3) has just been released with this feature implemented. I hope you find it helpful and would appreciate your feedback. Thanks!

**Comment by eyalbe4** [comment]
See the new `JF_INCLUDE_ALL_VULNERABILITIES` variable in the Frogbot documentation @jameselderxe.
